apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashulb1
  name: ashulb1 # change name of service
  namespace: ashu-space # adding namespace 
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # you have match label with pod template
   app: ashu-dep1 # update label of pod template section
  type: NodePort
status:
  loadBalancer: {}
